/**
 * SSE client for streaming quiz generation.
 * Receives questions in real-time as they're generated by the LLM.
 */

export interface QuizMetadata {
  id: string;
  title: string;
}

export interface QuizQuestion {
  id: string;
  type: string;
  text: string;
  options: string[];
  answerIndex: number;
  explanation?: string;
}

export interface StreamEvent {
  type: 'metadata' | 'question' | 'complete' | 'error';
  id?: string;
  title?: string;
  data?: QuizQuestion;
  total?: number;
  message?: string;
}

export class QuizStreamClient {
  private eventSource: EventSource | null = null;
  
  /**
   * Start streaming quiz generation
   * @param params Generation parameters
   * @param onMetadata Callback when quiz metadata arrives
   * @param onQuestion Callback when each question arrives
   * @param onComplete Callback when generation completes
   * @param onError Callback on error
   */
  async streamGenerate(
    params: {
      topic: string;
      difficulty: 'easy' | 'medium' | 'hard';
      num_questions: number;
      options_per_question?: number;
    },
    callbacks: {
      onMetadata?: (metadata: QuizMetadata) => void;
      onQuestion?: (question: QuizQuestion, index: number) => void;
      onComplete?: (totalQuestions: number) => void;
      onError?: (error: string) => void;
    }
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const queryParams = new URLSearchParams({
        topic: params.topic,
        difficulty: params.difficulty,
        num_questions: params.num_questions.toString(),
        options_per_question: (params.options_per_question || 4).toString(),
      });
      
      const url = `/api/quizzes/generate-stream?${queryParams}`;
      this.eventSource = new EventSource(url);
      
      let questionIndex = 0;
      
      this.eventSource.onmessage = (event) => {
        try {
          const payload: StreamEvent = JSON.parse(event.data);
          
          switch (payload.type) {
            case 'metadata':
              if (payload.id && payload.title) {
                callbacks.onMetadata?.({ id: payload.id, title: payload.title });
              }
              break;
            
            case 'question':
              if (payload.data) {
                callbacks.onQuestion?.(payload.data, questionIndex++);
              }
              break;
            
            case 'complete':
              callbacks.onComplete?.(payload.total || questionIndex);
              this.close();
              resolve();
              break;
            
            case 'error':
              callbacks.onError?.(payload.message || 'Unknown error');
              this.close();
              reject(new Error(payload.message || 'Stream error'));
              break;
          }
        } catch (err) {
          console.error('Failed to parse SSE event:', err);
          callbacks.onError?.('Failed to parse server response');
        }
      };
      
      this.eventSource.onerror = (err) => {
        console.error('SSE connection error:', err);
        callbacks.onError?.('Connection lost to server');
        this.close();
        reject(new Error('SSE connection failed'));
      };
    });
  }
  
  /**
   * Close the SSE connection
   */
  close(): void {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
  }
}

/**
 * Hook for using quiz streaming in React components
 */
export function useQuizStream() {
  const clientRef = { current: null as QuizStreamClient | null };
  
  const startStream = async (
    params: {
      topic: string;
      difficulty: 'easy' | 'medium' | 'hard';
      num_questions: number;
      options_per_question?: number;
    },
    callbacks: {
      onMetadata?: (metadata: QuizMetadata) => void;
      onQuestion?: (question: QuizQuestion, index: number) => void;
      onComplete?: (totalQuestions: number) => void;
      onError?: (error: string) => void;
    }
  ) => {
    if (clientRef.current) {
      clientRef.current.close();
    }
    
    clientRef.current = new QuizStreamClient();
    return clientRef.current.streamGenerate(params, callbacks);
  };
  
  const stopStream = () => {
    if (clientRef.current) {
      clientRef.current.close();
      clientRef.current = null;
    }
  };
  
  return { startStream, stopStream };
}
