export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  settings: '/settings',
  career: '/careers',   // matches your existing page: src/pages/careers.tsx
  courses: '/courses',
  mentors: '/mentors',
  mentorDashboard: '/mentors/dashboard',
  mentorSessions: '/mentors/dashboard/sessions',
  mentorEarnings: '/mentors/dashboard/earnings',
  mentorStudents: '/mentors/dashboard/students',
  mentorAnalytics: '/mentors/dashboard/analytics',
  mentorSettings: '/mentors/dashboard/settings',
  mentorBecome: '/mentors/become',
  ai: '/ai',
  faq: '/faq',
  paths: '/paths',
  pricing: '/pricing',
  logout: '/logout',
  profile: '/profile',
  resumeNew: '/resumes/new',
  resumes: '/resumes',
  quiz: (slug?: string | null) => slug ? `/quiz/${slug}` : '/paths',
  path: (slug?: string | null) => slug ? `/paths/${slug}` : '/paths',
};
