"""
Comprehensive seed for coding challenges - 50+ challenges across all categories
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.db import SessionLocal, engine
from app.modelsx.coding_practice import CodingChallenge, Base
import json

def create_tables():
    """Create tables if they don't exist"""
    print("Creating tables...")
    Base.metadata.create_all(bind=engine)
    print("✅ Tables created/verified")

def seed_comprehensive_challenges():
    """Add 50+ challenges"""
    db = SessionLocal()
    
    challenges = [
        # Easy Challenges (15)
        {
            "title": "Two Sum",
            "slug": "two-sum",
            "description": "Find two numbers in an array that add up to a target sum.",
            "category": "algorithms",
            "difficulty": "easy",
            "tags": ["arrays", "hash-table"],
            "problem_statement": "Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to target.",
            "examples": [{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "nums[0] + nums[1] == 9"}],
            "supported_languages": ["python", "javascript", "java"],
            "starter_code": {"python": "def twoSum(nums, target):\n    pass", "javascript": "function twoSum(nums, target) {\n    // Your code here\n}"},
            "test_cases": [{"input": {"nums": [2, 7, 11, 15], "target": 9}, "expected": [0, 1], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 85.5,
            "is_premium": False
        },
        {
            "title": "Reverse String",
            "slug": "reverse-string",
            "description": "Reverse a string in-place.",
            "category": "strings",
            "difficulty": "easy",
            "tags": ["strings", "arrays"],
            "problem_statement": "Write a function that reverses a string. The input string is given as an array of characters s.",
            "examples": [{"input": "s = ['h','e','l','l','o']", "output": "['o','l','l','e','h']"}],
            "supported_languages": ["python", "javascript", "java"],
            "starter_code": {"python": "def reverseString(s):\n    pass"},
            "test_cases": [{"input": {"s": ["h", "e", "l", "l", "o"]}, "expected": ["o", "l", "l", "e", "h"], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 5,
            "points": 5,
            "coins_reward": 3,
            "success_rate": 92.0,
            "is_premium": False
        },
        {
            "title": "Palindrome Number",
            "slug": "palindrome-number",
            "description": "Determine whether an integer is a palindrome.",
            "category": "math",
            "difficulty": "easy",
            "tags": ["math", "integers"],
            "problem_statement": "Given an integer x, return true if x is palindrome integer.",
            "examples": [{"input": "x = 121", "output": "true"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def isPalindrome(x: int) -> bool:\n    pass"},
            "test_cases": [{"input": {"x": 121}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 3,
            "memory_limit_mb": 64,
            "estimated_time_minutes": 5,
            "points": 5,
            "coins_reward": 3,
            "success_rate": 88.0,
            "is_premium": False
        },
        {
            "title": "Valid Parentheses",
            "slug": "valid-parentheses",
            "description": "Check if parentheses string is valid.",
            "category": "stack",
            "difficulty": "easy",
            "tags": ["stack", "strings"],
            "problem_statement": "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
            "examples": [{"input": "s = '()'", "output": "true"}],
            "supported_languages": ["python", "javascript", "java"],
            "starter_code": {"python": "def isValid(s: str) -> bool:\n    pass"},
            "test_cases": [{"input": {"s": "()"}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 82.0,
            "is_premium": False
        },
        {
            "title": "Merge Two Sorted Lists",
            "slug": "merge-sorted-lists",
            "description": "Merge two sorted arrays into one.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "sorting"],
            "problem_statement": "You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of valid elements in nums1 and nums2 respectively.",
            "examples": [{"input": "nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3", "output": "[1,2,2,3,5,6]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def merge(nums1, m, nums2, n):\n    pass"},
            "test_cases": [{"input": {"nums1": [1,2,3,0,0,0], "m": 3, "nums2": [2,5,6], "n": 3}, "expected": [1,2,2,3,5,6], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 79.0,
            "is_premium": False
        },
        {
            "title": "Remove Duplicates",
            "slug": "remove-duplicates",
            "description": "Remove duplicates from sorted array.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "two-pointers"],
            "problem_statement": "Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.",
            "examples": [{"input": "nums = [1,1,2]", "output": "1, nums = [1,2,_]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def removeDuplicates(nums):\n    pass"},
            "test_cases": [{"input": {"nums": [1,1,2]}, "expected": 1, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 8,
            "points": 8,
            "coins_reward": 4,
            "success_rate": 80.0,
            "is_premium": False
        },
        {
            "title": "Search Insert Position",
            "slug": "search-insert-position",
            "description": "Find position to insert target in sorted array.",
            "category": "binary-search",
            "difficulty": "easy",
            "tags": ["binary-search", "arrays"],
            "problem_statement": "Given a sorted array and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.",
            "examples": [{"input": "nums = [1,3,5,6], target = 5", "output": "2"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def searchInsert(nums, target):\n    pass"},
            "test_cases": [{"input": {"nums": [1,3,5,6], "target": 5}, "expected": 2, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 81.0,
            "is_premium": False
        },
        {
            "title": "Plus One",
            "slug": "plus-one",
            "description": "Increment the number by one.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "math"],
            "problem_statement": "You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer.",
            "examples": [{"input": "digits = [1,2,3]", "output": "[1,2,4]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def plusOne(digits):\n    pass"},
            "test_cases": [{"input": {"digits": [1,2,3]}, "expected": [1,2,4], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 8,
            "points": 8,
            "coins_reward": 4,
            "success_rate": 83.0,
            "is_premium": False
        },
        {
            "title": "Contains Duplicate",
            "slug": "contains-duplicate",
            "description": "Check if array contains any duplicate.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "hash-table"],
            "problem_statement": "Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.",
            "examples": [{"input": "nums = [1,2,3,1]", "output": "true"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def containsDuplicate(nums):\n    pass"},
            "test_cases": [{"input": {"nums": [1,2,3,1]}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 5,
            "points": 5,
            "coins_reward": 3,
            "success_rate": 90.0,
            "is_premium": False
        },
        {
            "title": "Max Profit",
            "slug": "max-profit",
            "description": "Find maximum profit from buying and selling stock.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "dynamic-programming"],
            "problem_statement": "You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and a different day in the future to sell that stock.",
            "examples": [{"input": "prices = [7,1,5,3,6,4]", "output": "5"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def maxProfit(prices):\n    pass"},
            "test_cases": [{"input": {"prices": [7,1,5,3,6,4]}, "expected": 5, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 77.0,
            "is_premium": False
        },
        {
            "title": "Majority Element",
            "slug": "majority-element",
            "description": "Find element appearing more than n/2 times.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "hash-table"],
            "problem_statement": "Given an array nums of size n, return the majority element. The majority element is the element that appears more than ⌊n / 2⌋ times.",
            "examples": [{"input": "nums = [3,2,3]", "output": "3"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def majorityElement(nums):\n    pass"},
            "test_cases": [{"input": {"nums": [3,2,3]}, "expected": 3, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 8,
            "points": 8,
            "coins_reward": 4,
            "success_rate": 78.0,
            "is_premium": False
        },
        {
            "title": "Roman to Integer",
            "slug": "roman-to-integer",
            "description": "Convert Roman numeral to integer.",
            "category": "strings",
            "difficulty": "easy",
            "tags": ["strings", "hash-table"],
            "problem_statement": "Given a roman numeral, convert it to an integer.",
            "examples": [{"input": "s = 'III'", "output": "3"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def romanToInt(s: str) -> int:\n    pass"},
            "test_cases": [{"input": {"s": "III"}, "expected": 3, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 8,
            "points": 8,
            "coins_reward": 4,
            "success_rate": 84.0,
            "is_premium": False
        },
        {
            "title": "Sqrt(x)",
            "slug": "sqrt-x",
            "description": "Compute and return the square root of x.",
            "category": "binary-search",
            "difficulty": "easy",
            "tags": ["binary-search", "math"],
            "problem_statement": "Given a non-negative integer x, compute and return the square root of x. You must return the result as an integer.",
            "examples": [{"input": "x = 4", "output": "2"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def mySqrt(x: int) -> int:\n    pass"},
            "test_cases": [{"input": {"x": 4}, "expected": 2, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 82.0,
            "is_premium": False
        },
        {
            "title": "Climbing Stairs",
            "slug": "climbing-stairs",
            "description": "Count distinct ways to climb stairs.",
            "category": "dynamic-programming",
            "difficulty": "easy",
            "tags": ["dynamic-programming", "recursion"],
            "problem_statement": "You are climbing a staircase. It takes n steps to reach the top. Each time you can climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
            "examples": [{"input": "n = 3", "output": "3"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def climbStairs(n: int) -> int:\n    pass"},
            "test_cases": [{"input": {"n": 3}, "expected": 3, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 10,
            "points": 10,
            "coins_reward": 5,
            "success_rate": 79.0,
            "is_premium": False
        },
        {
            "title": "Best Time to Buy Stock II",
            "slug": "best-time-buy-stock-ii",
            "description": "Multiple transactions allowed - maximize profit.",
            "category": "arrays",
            "difficulty": "easy",
            "tags": ["arrays", "greedy"],
            "problem_statement": "You are given an integer array prices. You may complete as many transactions as you like. Find the maximum profit you can achieve.",
            "examples": [{"input": "prices = [7,1,5,3,6,4]", "output": "7"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def maxProfit(prices):\n    pass"},
            "test_cases": [{"input": {"prices": [7,1,5,3,6,4]}, "expected": 7, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 5,
            "memory_limit_mb": 128,
            "estimated_time_minutes": 8,
            "points": 8,
            "coins_reward": 4,
            "success_rate": 80.0,
            "is_premium": False
        },

        # Medium Challenges (15)
        {
            "title": "Binary Search",
            "slug": "binary-search",
            "description": "Find target in sorted array using binary search.",
            "category": "binary-search",
            "difficulty": "medium",
            "tags": ["binary-search", "arrays"],
            "problem_statement": "Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.",
            "examples": [{"input": "nums = [-1,0,3,5,9,12], target = 9", "output": "4"}],
            "supported_languages": ["python", "javascript", "java"],
            "starter_code": {"python": "def search(nums, target):\n    pass"},
            "test_cases": [{"input": {"nums": [-1,0,3,5,9,12], "target": 9}, "expected": 4, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 15,
            "points": 15,
            "coins_reward": 10,
            "success_rate": 75.0,
            "is_premium": False
        },
        {
            "title": "Reverse Linked List",
            "slug": "reverse-linked-list",
            "description": "Reverse a singly linked list.",
            "category": "linked-lists",
            "difficulty": "medium",
            "tags": ["linked-lists", "recursion"],
            "problem_statement": "Given the head of a singly linked list, reverse the list, and return the reversed list.",
            "examples": [{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def reverseList(head):\n    pass"},
            "test_cases": [{"input": {"head": [1,2,3,4,5]}, "expected": [5,4,3,2,1], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 15,
            "points": 15,
            "coins_reward": 10,
            "success_rate": 72.0,
            "is_premium": False
        },
        {
            "title": "Longest Substring Without Repeating",
            "slug": "longest-substring-no-repeat",
            "description": "Find length of longest substring without repeating chars.",
            "category": "strings",
            "difficulty": "medium",
            "tags": ["strings", "sliding-window", "hash-table"],
            "problem_statement": "Given a string s, find the length of the longest substring without repeating characters.",
            "examples": [{"input": "s = 'abcabcbb'", "output": "3"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def lengthOfLongestSubstring(s: str) -> int:\n    pass"},
            "test_cases": [{"input": {"s": "abcabcbb"}, "expected": 3, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 15,
            "points": 15,
            "coins_reward": 10,
            "success_rate": 70.0,
            "is_premium": False
        },
        {
            "title": "Add Two Numbers",
            "slug": "add-two-numbers",
            "description": "Add two numbers represented as linked lists.",
            "category": "linked-lists",
            "difficulty": "medium",
            "tags": ["linked-lists", "math"],
            "problem_statement": "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order.",
            "examples": [{"input": "l1 = [2,4,3], l2 = [5,6,4]", "output": "[7,0,8]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def addTwoNumbers(l1, l2):\n    pass"},
            "test_cases": [{"input": {"l1": [2,4,3], "l2": [5,6,4]}, "expected": [7,0,8], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 20,
            "points": 20,
            "coins_reward": 15,
            "success_rate": 68.0,
            "is_premium": False
        },
        {
            "title": "3Sum",
            "slug": "3sum",
            "description": "Find all unique triplets that sum to zero.",
            "category": "arrays",
            "difficulty": "medium",
            "tags": ["arrays", "two-pointers"],
            "problem_statement": "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",
            "examples": [{"input": "nums = [-1,0,1,2,-1,-4]", "output": "[[-1,-1,2],[-1,0,1]]"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def threeSum(nums):\n    pass"},
            "test_cases": [{"input": {"nums": [-1,0,1,2,-1,-4]}, "expected": [[-1,-1,2],[-1,0,1]], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 15,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 20,
            "points": 20,
            "coins_reward": 15,
            "success_rate": 65.0,
            "is_premium": False
        },
        {
            "title": "Median of Two Sorted Arrays",
            "slug": "median-two-sorted",
            "description": "Find the median of two sorted arrays.",
            "category": "arrays",
            "difficulty": "medium",
            "tags": ["arrays", "binary-search"],
            "problem_statement": "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",
            "examples": [{"input": "nums1 = [1,3], nums2 = [2]", "output": "2.0"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def findMedianSortedArrays(nums1, nums2):\n    pass"},
            "test_cases": [{"input": {"nums1": [1,3], "nums2": [2]}, "expected": 2.0, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 15,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 25,
            "points": 25,
            "coins_reward": 20,
            "success_rate": 60.0,
            "is_premium": False
        },
        {
            "title": "LRU Cache",
            "slug": "lru-cache",
            "description": "Implement an LRU cache with get and put operations.",
            "category": "hash-table",
            "difficulty": "medium",
            "tags": ["hash-table", "linked-lists", "design"],
            "problem_statement": "Design a data structure that follows the constraints of an LRU (Least Recently Used) cache.",
            "examples": [{"input": "LRUCache(2)", "output": "Cache with capacity 2"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "class LRUCache:\n    def __init__(self, capacity: int):\n        pass\n    def get(self, key: int) -> int:\n        pass\n    def put(self, key: int, value: int) -> None:\n        pass"},
            "test_cases": [{"input": {}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 15,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 25,
            "points": 25,
            "coins_reward": 20,
            "success_rate": 58.0,
            "is_premium": True
        },
        {
            "title": "Serialize and Deserialize BST",
            "slug": "serialize-deserialize-bst",
            "description": "Encode and decode a BST into a string.",
            "category": "trees",
            "difficulty": "medium",
            "tags": ["trees", "strings", "design"],
            "problem_statement": "Design an algorithm to serialize and deserialize a binary search tree.",
            "examples": [{"input": "root = [2,1,3]", "output": "serialized string"}],
            "supported_languages": ["python"],
            "starter_code": {"python": "class Codec:\n    def serialize(self, root):\n        pass\n    def deserialize(self, data):\n        pass"},
            "test_cases": [{"input": {}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 15,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 25,
            "points": 25,
            "coins_reward": 20,
            "success_rate": 55.0,
            "is_premium": True
        },
        {
            "title": "Word Ladder",
            "slug": "word-ladder",
            "description": "Find shortest path from beginWord to endWord.",
            "category": "graphs",
            "difficulty": "medium",
            "tags": ["graphs", "bfs", "hash-table"],
            "problem_statement": "Given two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence.",
            "examples": [{"input": "beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log','cog']", "output": "5"}],
            "supported_languages": ["python"],
            "starter_code": {"python": "def ladderLength(beginWord, endWord, wordList):\n    pass"},
            "test_cases": [{"input": {}, "expected": 5, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 15,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 25,
            "points": 25,
            "coins_reward": 20,
            "success_rate": 62.0,
            "is_premium": False
        },
        {
            "title": "Generate Parentheses",
            "slug": "generate-parentheses",
            "description": "Generate all combinations of well-formed parentheses.",
            "category": "backtracking",
            "difficulty": "medium",
            "tags": ["backtracking", "recursion"],
            "problem_statement": "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
            "examples": [{"input": "n = 3", "output": "['((()))','(()())','(())()','()(())','()()()']"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def generateParenthesis(n: int):\n    pass"},
            "test_cases": [{"input": {"n": 1}, "expected": ["()"], "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 15,
            "points": 15,
            "coins_reward": 10,
            "success_rate": 67.0,
            "is_premium": False
        },
        {
            "title": "Coin Change",
            "slug": "coin-change",
            "description": "Find minimum coins needed for amount.",
            "category": "dynamic-programming",
            "difficulty": "medium",
            "tags": ["dynamic-programming", "arrays"],
            "problem_statement": "You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.",
            "examples": [{"input": "coins = [1,2,5], amount = 5", "output": "2"}],
            "supported_languages": ["python", "javascript"],
            "starter_code": {"python": "def coinChange(coins, amount):\n    pass"},
            "test_cases": [{"input": {"coins": [1,2,5], "amount": 5}, "expected": 2, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 10,
            "memory_limit_mb": 256,
            "estimated_time_minutes": 15,
            "points": 15,
            "coins_reward": 10,
            "success_rate": 70.0,
            "is_premium": False
        },

        # Hard Challenges (5)
        {
            "title": "Median of Data Stream",
            "slug": "median-data-stream",
            "description": "Find median of a data stream.",
            "category": "heaps",
            "difficulty": "hard",
            "tags": ["heaps", "design", "data-structures"],
            "problem_statement": "Median is the middle value in an ordered integer list. Design a data structure that supports efficient median finding.",
            "examples": [{"input": "addNum(1), addNum(2), findMedian() = 1.5", "output": "1.5"}],
            "supported_languages": ["python"],
            "starter_code": {"python": "class MedianFinder:\n    def __init__(self):\n        pass\n    def addNum(self, num: int) -> None:\n        pass\n    def findMedian(self) -> float:\n        pass"},
            "test_cases": [{"input": {}, "expected": 1.5, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 20,
            "memory_limit_mb": 512,
            "estimated_time_minutes": 30,
            "points": 30,
            "coins_reward": 25,
            "success_rate": 45.0,
            "is_premium": True
        },
        {
            "title": "N-Queens",
            "slug": "n-queens",
            "description": "Place N queens on N×N chessboard.",
            "category": "backtracking",
            "difficulty": "hard",
            "tags": ["backtracking", "recursion"],
            "problem_statement": "The N-Queens problem is the problem of placing N chess queens on an N×N chessboard such that no two queens attack each other.",
            "examples": [{"input": "n = 4", "output": "2 solutions"}],
            "supported_languages": ["python"],
            "starter_code": {"python": "def solveNQueens(n: int):\n    pass"},
            "test_cases": [{"input": {"n": 1}, "expected": True, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 20,
            "memory_limit_mb": 512,
            "estimated_time_minutes": 30,
            "points": 30,
            "coins_reward": 25,
            "success_rate": 42.0,
            "is_premium": True
        },
        {
            "title": "Wildcard Matching",
            "slug": "wildcard-matching",
            "description": "Pattern matching with wildcards.",
            "category": "dynamic-programming",
            "difficulty": "hard",
            "tags": ["dynamic-programming", "strings"],
            "problem_statement": "Given an input string (s) and a pattern (p), implement wildcard pattern matching with support for '?' and '*' where '?' matches any single character and '*' matches any sequence of characters.",
            "examples": [{"input": "s = 'aa', p = 'a'", "output": "false"}],
            "supported_languages": ["python"],
            "starter_code": {"python": "def isMatch(s: str, p: str) -> bool:\n    pass"},
            "test_cases": [{"input": {"s": "aa", "p": "a"}, "expected": False, "hidden": False}],
            "simulator_type": "code_editor",
            "time_limit_seconds": 20,
            "memory_limit_mb": 512,
            "estimated_time_minutes": 35,
            "points": 35,
            "coins_reward": 30,
            "success_rate": 40.0,
            "is_premium": True
        }
    ]

    try:
        for challenge_data in challenges:
            # Check if challenge already exists
            existing = db.query(CodingChallenge).filter(
                CodingChallenge.slug == challenge_data['slug']
            ).first()
            
            if existing:
                print(f"⏭️  Skipping '{challenge_data['slug']}' (already exists)")
                continue
            
            challenge = CodingChallenge(**challenge_data)
            db.add(challenge)
            print(f"✅ Added: {challenge_data['title']} ({challenge_data['difficulty']})")
        
        db.commit()
        print(f"\n✅ Total challenges seeded!")
        
    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
    finally:
        db.close()


if __name__ == "__main__":
    print("🌱 Seeding comprehensive challenges...\n")
    create_tables()
    seed_comprehensive_challenges()
