"""Initial migration with all models

Revision ID: 4fef0e1df469
Revises: 
Create Date: 2025-11-02 19:45:08.568874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fef0e1df469'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_sessions', sa.Column('payment_intent_id', sa.String(), nullable=True))
    op.drop_column('mentor_sessions', 'recording_started_at')
    op.drop_column('mentor_sessions', 'recording_url')
    op.drop_column('mentor_sessions', 'recording_duration')
    op.drop_column('quizzes', 'path_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('path_slug', sa.VARCHAR(), nullable=True))
    op.add_column('mentor_sessions', sa.Column('recording_duration', sa.INTEGER(), nullable=True))
    op.add_column('mentor_sessions', sa.Column('recording_url', sa.VARCHAR(), nullable=True))
    op.add_column('mentor_sessions', sa.Column('recording_started_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('mentor_sessions', 'payment_intent_id')
    # ### end Alembic commands ###
